
const TYPE={
    ADD_PRODUCT:"ADD_PRODUCT",
    REMOVE_PRODUCT:"REMOVE_PRODUCT",
    REMOVE_ALL_PRODUCTS:"REMOVE_ALL_PRODUCTS",
    CLEAR_PRODUCTS:"CLEAR_PRODUCTS",
    SHOW_PRODUCT:"SHOW_PRODUCT",
    SUM_TOTAL:"SUM_TOTAL"
}

export { TYPE }